
#include <stdio.h>

#include "bitops.h"
#include "task_sched.h"

// NOTE: #X means "wrap the value of X in double quotes, without macro expansion".
#define PRINTLN_SYM(S, F) printf(#S "=%" #F "\n", S)

int main(int argc, char **argv) {
	sched_time t;
	
	// NOTE: Binary constants are apparenly a GNU thing.
	PRINTLN_SYM(SCHED_CLOCK_PRESCALE, d);
	PRINTLN_SYM(SCHED_TICK_MUSECS, d);
	PRINTLN_SYM(MUSECS_TO_SCHED_TICKS(10), d);
	PRINTLN_SYM(SCHED_TICKS_TO_MUSECS(10), d);
	PRINTLN_SYM(MUSECS_TO_SCHED_SMALLTICKS(5000), d);
	PRINTLN_SYM(MUSECS_TO_SCHED_BIGTICKS(5000), d);
	PRINTLN_SYM(SCHED_BIGTICKS_TO_MUSECS(10), d);
	
	PRINTLN_SYM(SCHED_TIME_MAX_TICKS, 08X);
	PRINTLN_SYM(SCHED_TIME_MAX_MUSECS, u);
	PRINTLN_SYM(SCHED_TIME_MAX_MS, u);
	
	PRINTLN_SYM(SCHED_MIN_DELTA_TICKS, d);
	PRINTLN_SYM(SCHED_MIN_DELTA_L, d);
	PRINTLN_SYM(SCHED_MIN_DELTA_H, d);
	
	PRINTLN_SYM(BITSTATES(5), d);
	PRINTLN_SYM(BITMAX(5), d);
	PRINTLN_SYM(BITMASK_AT(2, 5), 02X);
	PRINTLN_SYM(GET_BITFIELD_AT(3, 4, 0b11011001), d);
	PRINTLN_SYM(SET_BITFIELD_AT(3, 4, 0b11011001, 2), 02X);
	
	PRINTLN_SYM(TASK_ST_NUM_OFFS, d);
	PRINTLN_SYM(TASK_ST_NUM_BITS, d);
	PRINTLN_SYM(TASK_ST_N_NUMS, d);
	PRINTLN_SYM(TASK_ST_MAX_NUM, d);
	PRINTLN_SYM(TASK_ST_NUM_MASK, 02X);
	PRINTLN_SYM(TASK_ST_GET_NUM(0b10110011), d);
	PRINTLN_SYM(TASK_ST_SET_NUM(0b10110011, 4), 02X);
	PRINTLN_SYM(TASK_ST_NUM(4), 02X);
	
	PRINTLN_SYM(TASK_ST_CAT_OFFS, d);
	PRINTLN_SYM(TASK_ST_CAT_BITS, d);
	PRINTLN_SYM(TASK_ST_N_CATS, d);
	PRINTLN_SYM(TASK_ST_MAX_CAT, d);
	PRINTLN_SYM(TASK_ST_CAT_MASK, 02X);
	PRINTLN_SYM(TASK_ST_GET_CAT(0b10110011), d);
	PRINTLN_SYM(TASK_ST_SET_CAT(0b10110011, 12), 02X);
	PRINTLN_SYM(TASK_ST_CAT(12), 02X);
	
	PRINTLN_SYM(TASK_ST_NUM_CAT_MASK, 02X);
	
	PRINTLN_SYM(TASK_ST_SLP_OFFS, d);
	PRINTLN_SYM(TASK_ST_SLP_BITS, d);
	PRINTLN_SYM(TASK_ST_SLP_MASK, 02X);
	PRINTLN_SYM(TASK_ST_GET_SLP(0b10110011), d);
	PRINTLN_SYM(TASK_ST_SET_SLP(0b10110011, 0), 02X);
	PRINTLN_SYM(TASK_ST_SLP(1), 02X);
	
	PRINTLN_SYM(TASK_ST_MAKE(4, 12, 1), 02X);
	
	t = SCHED_TIME_LH(10, 20);
	PRINTLN_SYM(t.l, d);
	PRINTLN_SYM(t.h, d);
	t = SCHED_TIME_MUSECS(1030);
	PRINTLN_SYM(SCHED_TIME_TO_MUSECS(t), d);
	PRINTLN_SYM(t.l, d);
	PRINTLN_SYM(t.h, d);
	t = SCHED_TIME_MS(800);
	PRINTLN_SYM(t.l, d);
	PRINTLN_SYM(t.h, d);
	t = sched_time_add(t, SCHED_TIME_MS(500));
	PRINTLN_SYM(SCHED_TIME_TO_MS(t), d);
	PRINTLN_SYM(t.l, d);
	PRINTLN_SYM(t.h, d);
	t = sched_time_sub(t, SCHED_TIME_MS(250));
	PRINTLN_SYM(SCHED_TIME_TO_MS(t), d);
	PRINTLN_SYM(t.l, d);
	PRINTLN_SYM(t.h, d);
	
	return 0;
}
