
#include <stdio.h>

#define SCHED_HEADER_TEST
#include "task_sched.h"

// NOTE: #X means "wrap the value of X in double quotes, without macro expansion".
#define PRINT_SYM(S, F) printf(#S "=%" #F "\n", S)

int main(int argc, char **argv) {
	sched_time t;
	
	// NOTE: Binary constants are apparenly a GNU thing.
	PRINT_SYM(SCHED_CLOCK_PRESCALE, d);
	PRINT_SYM(SCHED_TICK_MUSECS, d);
	PRINT_SYM(MUSECS_TO_SCHED_TICKS(10), d);
	PRINT_SYM(SCHED_TICKS_TO_MUSECS(10), d);
	PRINT_SYM(MUSECS_TO_SCHED_SMALLTICKS(5000), d);
	PRINT_SYM(MUSECS_TO_SCHED_BIGTICKS(5000), d);
	PRINT_SYM(SCHED_BIGTICKS_TO_MUSECS(10), d);
	
	PRINT_SYM(SCHED_MIN_DELTA_TICKS, d);
	PRINT_SYM(SCHED_MIN_DELTA_L, d);
	PRINT_SYM(SCHED_MIN_DELTA_H, d);
	
	PRINT_SYM(TASK_ST_N(5), d);
	PRINT_SYM(TASK_ST_MAX(5), d);
	PRINT_SYM(TASK_ST_MASK(2, 5), 02X);
	PRINT_SYM(TASK_ST_GET(4, 0b01110000, 0b11011001), d);
	PRINT_SYM(TASK_ST_SET(4, 0b01110000, 0b11011001, 2), 02X);
	
	PRINT_SYM(TASK_ST_NUM_OFFS, d);
	PRINT_SYM(TASK_ST_NUM_BITS, d);
	PRINT_SYM(TASK_ST_N_NUMS, d);
	PRINT_SYM(TASK_ST_MAX_NUM, d);
	PRINT_SYM(TASK_ST_NUM_MASK, 02X);
	PRINT_SYM(TASK_ST_GET_NUM(0b10110011), d);
	PRINT_SYM(TASK_ST_SET_NUM(0b10110011, 4), 02X);
	PRINT_SYM(TASK_ST_NUM(4), 02X);
	
	PRINT_SYM(TASK_ST_CAT_OFFS, d);
	PRINT_SYM(TASK_ST_CAT_BITS, d);
	PRINT_SYM(TASK_ST_N_CATS, d);
	PRINT_SYM(TASK_ST_MAX_CAT, d);
	PRINT_SYM(TASK_ST_CAT_MASK, 02X);
	PRINT_SYM(TASK_ST_GET_CAT(0b10110011), d);
	PRINT_SYM(TASK_ST_SET_CAT(0b10110011, 12), 02X);
	PRINT_SYM(TASK_ST_CAT(12), 02X);
	
	PRINT_SYM(TASK_ST_NUM_CAT_MASK, 02X);
	
	PRINT_SYM(TASK_ST_SLP_OFFS, d);
	PRINT_SYM(TASK_ST_SLP_BITS, d);
	PRINT_SYM(TASK_ST_SLP_MASK, 02X);
	PRINT_SYM(TASK_ST_GET_SLP(0b10110011), d);
	PRINT_SYM(TASK_ST_SET_SLP(0b10110011, 0), 02X);
	PRINT_SYM(TASK_ST_SLP(1), 02X);
	
	PRINT_SYM(TASK_ST_MAKE(4, 12, 1), 02X);
	
	t = SCHED_TIME_LH(10, 20);
	PRINT_SYM(t.l, d);
	PRINT_SYM(t.h, d);
	t = SCHED_TIME_MUSECS(1030);
	PRINT_SYM(t.l, d);
	PRINT_SYM(t.h, d);
	t = SCHED_TIME_MS(1000);
	PRINT_SYM(t.l, d);
	PRINT_SYM(t.h, d);
	
	return 0;
}
