
name: build-docs
run-name: 'Building API documentation with NaturalDocs'
on:
  push:
    branches: [ main ]
jobs:
  naturaldocs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install-nd
        run: sudo apt-get -y install naturaldocs
      - name: make-c-doc
        working-directory: ./avr
        run: make doc
      - name: make-py-doc
        working-directory: ./python
        run: make doc
      - name: mkdir-pages
        run: mkdir pages
      - name: cp-pages
        run: |
          cp pages_files/*.html pages_files/*.css pages
          cp -rT avr/docs/natural pages/avr
          cp -rT python/docs/natural pages/python
      - name: upload-artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'pages/'
